apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:Rp3AuMyhgXXsJoNs9Bxm9zBpc+sdpxc5NNcv22Ta5/nlU/aB+QyrrsroLa6MO01FS2WVYWHAD/nLKpxon0ccvAq6kbp/LYf/fWm+EF/dLkD/FqoIVQwuIXaWHLBbNIpNMWW7Zlw2I8hTdjkISDckN5+vGQMTxtRLYa0rcg==,iv:gjH6theN0CF2SvzP/GG1nxUpxIGqZst29FjolM+nYm0=,tag:3vp6LmxVc/Pmk2SHeTK2ww==,type:str]
kind: Secret
metadata:
    name: renovate-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMFpUTmljaGs3WDc4TEZQ
            M0sySWM4MzJjVFI3akEwN2Rsdm0wY0lJWkJNCk03NTFKYkR6WG45QmEzR2F2eU5D
            WEo1dW00RGIrbFM2KzZGTDU5REhZdUkKLS0tIFI1N09UbkFRaHo3MjRPZmFvdklD
            dVRkdk1xMElseGRWeG8rTE1WK3NiTUEKE6kZiRcSOywG3fx4HYMBRzYVtHxEaPQX
            zNIBklXSNDCQTAtn8ZgcOGMtr3nKn5xOpcGXO+drM3WXtAxepvnKNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17c433epg3dz53g3w3dd6f427spj6m8heh0h378njpdgdktusydhqvv9l32
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T12:17:16Z"
    mac: ENC[AES256_GCM,data:NfXAAMpsW1M1veRUKYRHjic3S6KHoEgIoaxe84UtZPpgoWDSJcSq41e3uJZnGowS3x584JxhUFKVp76RMpoyjYckxeoykJRwpdsquVm4FMAHJ0zEszYpT/AbfPqIkh0tgQX6ppDmWOWNpgKJifXYIuf99XxrPMS7V4GPD4F8zxQ=,iv:0ik6qdBWGmTIJ7O3RJw3ZdSlCU/yixyCQdQqNI2EsyY=,tag:sQBGknxkKxe8O3RN5LG/yQ==,type:str]
    version: 3.13.1