apiVersion: apps/v1
kind: Deployment
metadata:
  name: fgcl
  namespace: fgcl
  labels:
    app: fgcl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fgcl
  template:
    metadata:
      labels:
        app: fgcl
    spec:
      containers:
        - name: fgcl
          image: ghcr.io/ivaylo-iv/lottery-draw:cec6e83cb7d9ec63642bbf9b26cd2697bf8d3ab9
          ports:
            - containerPort: 3000
