apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KuLGegrCZy0m7UioU99nMVZdbbhDUN9R5qlWgJw+Z2yajX2rSnaoeSighxKG+l6D9X4fEUbTQUaYRBf6s60dSk1naUXHabN5OqOvAEU25HcYKYn3hvUn4A==,iv:cyLvwU1mJREla6m3YHJRog+B+tlYm1PKgjqxc5GhDCM=,tag:Skpyx4OUJVaFkNMXsLKucg==,type:str]
    user: ENC[AES256_GCM,data:ODHZySjSGajZxtP4eAW0EBZ+o7Y=,iv:e/iMA17u+EA8dJmttxnve6hnN8eEXt5hUn4g9QLjqfI=,tag:fUhONCA8WPRuyKmBJfWlCA==,type:str]
kind: Secret
metadata:
    name: grafana-monitoring-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUNCdUhrbitHUnYrOXhy
            MEIwSFhyOEh3Qno5MERsdUpweExjT1lDbVhVClIwbmJNZUJOcUxzY2NsSWF2cW1r
            ZjZ3aStLMXJGSGttcjNuNUhJSVdNWVEKLS0tIGJRRVhheXZRS2p2dnpBck9yK1Fy
            TFBDajNtVG8vYzd1L2M0K2RvT2dlV2MKEGrDUg05uaTuCpKk7lOIW1GtgRuXOPqu
            eOKD+ZJAOHzmPqGptpon/zXC/oySjU5nWJiiIngEJNdeE+8FpeBCrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17c433epg3dz53g3w3dd6f427spj6m8heh0h378njpdgdktusydhqvv9l32
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T12:25:35Z"
    mac: ENC[AES256_GCM,data:1y4ql3mnM1F6XqsEyTbLzEhrZptulQt69XjpKxDgQBPBcbjWOOCLD/t03JgeeaEgrLGsqqNeKmfeMNB+p0gBbsfwwdUUJGX3C/0iYqUro8dP5YW9fHkNGG6YD1Fmem2bCBpw/BIW5Uaqy4wwA6fDiwbO0AG6NKGBKwVHe6UVsJA=,iv:e/neb759Iv6tekRUqFP+BbJotiqPq04MnL7uUy+oAro=,tag:5HwcQjM5d/WfvfRAm/MKrQ==,type:str]
    version: 3.13.1